version: '3'
services:
   dnsmasq:
      build: ./dnsmasq/
      network_mode: "host"
      env_file: ./dnsmasq/env_file
      restart: always
   tftp:
       build: ./tftp/
       ports:
       - "69:69/udp"
       volumes:
       - ./tftp/files:/var/tftpboot:ro
       restart: always
   webserver:
      image: nginx:alpine
      ports:
      - 80:80
      volumes:
      - ./webserver/files:/usr/share/nginx/html
      restart: always
